### PR TITLE
feat: add fish and bash completions

### LINKED ISSUE #21: Add shell autocompletion
Some cluster names are long, so it would be nice to have autocompletion for the `use`, `view`, and `rm` commands based on the output of `kconf ls`.

### PR DESCRIPTION
**Pull request by Ulexus**
add fish and bash completions

## What? (description)

Adds command completions for fish shell and bash.

## Why? (reasoning)

Long or poorly-remembered contexts are less of a problem when the machine does the hunting.

## GitHub Issue (if applicable)
[closes #21]

## Acceptance
Check your PR for the following:

- [ ] you included tests
- [ ] you linted your code
- [ ] your PR has only one commit (interactive rebase!)
- [ ] your commit message follows Conventional Commit format
- [ ] you are not reducing the total test coverage

### CODE REVIEW

**Comment by particledecay** [comment]
@Ulexus I haven't been able to get the namespace completion working in either bash or fish. Is this working on your end?

**Comment by Ulexus** [comment]
It here here in fish, yes.  However, since it has to know what the context is before it can complete the namespace, the `-n` does have to come _after_ the context name.

**Comment by particledecay** [comment]
@Ulexus to be honest, I think I would prefer this functionality to exist within the binary (i.e. `kconf completion bash`). I appreciate the PR but I'd like to follow more k8s-like conventions elsewhere (like `kubectl`).

**Comment by Ulexus** [comment]
I wholly agree!

**Comment by Ulexus** [comment]
I just rewrote this PR to use cobra's method.  MUCH EASIER!  I can open a new PR if you don't want to reopen this one.  Just let me know.

**Comment by Ulexus** [comment]
Hmm.  It doesn't look like the PR is updating now that it is closed; I'll open a new one.

**Pull request closed without merging**
